<a href="https://colab.research.google.com/github/vaishnavikokate20-debug/AIML/blob/main/Ann_Classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df=pd.read_csv("DateFruit_Dataset.csv")

In [ ]:
df.head()

,AREA,PERIMETER,MAJOR_AXIS,MINOR_AXIS,ECCENTRICITY,EQDIASQ,SOLIDITY,CONVEX_AREA,EXTENT,ASPECT_RATIO,...,KurtosisRR,KurtosisRG,KurtosisRB,EntropyRR,EntropyRG,EntropyRB,ALLdaub4RR,ALLdaub4RG,ALLdaub4RB,Class
0,422163,2378.908,837.8484,645.6693,0.6373,733.1539,0.9947,424428,0.7831,1.2976,...,3.2370,2.9574,4.2287,-59191263232,-50714214400,-39922372608,58.7255,54.9554,47.8400,BERHI
1,338136,2085.144,723.8198,595.2073,0.5690,656.1464,0.9974,339014,0.7795,1.2161,...,2.6228,2.6350,3.1704,-34233065472,-37462601728,-31477794816,50.0259,52.8168,47.8315,BERHI
2,526843,2647.394,940.7379,715.3638,0.6494,819.0222,0.9962,528876,0.7657,1.3150,...,3.7516,3.8611,4.7192,-93948354560,-74738221056,-60311207936,65.4772,59.2860,51.9378,BERHI
3,416063,2351.210,827.9804,645.2988,0.6266,727.8378,0.9948,418255,0.7759,1.2831,...,5.0401,8.6136,8.2618,-32074307584,-32060925952,-29575010304,43.3900,44.1259,41.1882,BERHI
4,347562,2160.354,763.9877,582.8359,0.6465,665.2291,0.9908,350797,0.7569,1.3108,...,2.7016,2.9761,4.4146,-39980974080,-35980042240,-25593278464,52.7743,50.9080,42.6666,BERHI

In [ ]:
df.isnull().sum()

AREA             0
PERIMETER        0
MAJOR_AXIS       0
MINOR_AXIS       0
ECCENTRICITY     0
EQDIASQ          0
SOLIDITY         0
CONVEX_AREA      0
EXTENT           0
ASPECT_RATIO     0
ROUNDNESS        0
COMPACTNESS      0
SHAPEFACTOR_1    0
SHAPEFACTOR_2    0
SHAPEFACTOR_3    0
SHAPEFACTOR_4    0
MeanRR           0
MeanRG           0
MeanRB           0
StdDevRR         0
StdDevRG         0
StdDevRB         0
SkewRR           0
SkewRG           0
SkewRB           0
KurtosisRR       0
KurtosisRG       0
KurtosisRB       0
EntropyRR        0
EntropyRG        0
EntropyRB        0
ALLdaub4RR       0
ALLdaub4RG       0
ALLdaub4RB       0
Class            0
dtype: int64

In [ ]:
df.shape

(898, 35)

In [ ]:
X=df.drop("Class",axis=1)
y=df["Class"]

In [ ]:
df["Class"].unique()

array(['BERHI', 'DEGLET', 'DOKOL', 'IRAQI', 'ROTANA', 'SAFAVI', 'SOGAY'],
      dtype=object)

In [ ]:
from sklearn.preprocessing import LabelEncoder,StandardScaler
le=LabelEncoder()
y=le.fit_transform(y)

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(
    X,y,test_size=0.2,random_state=42
)

In [ ]:
scaler=StandardScaler()
X_train_scaled=scaler.fit_transform(X_train)
X_test_scaled=scaler.transform(X_test)

In [ ]:
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader,TensorDataset

In [ ]:
X_train_tensor=torch.tensor(X_train_scaled,dtype=torch.float32)
y_train_tensor=torch.tensor(y_train,dtype=torch.long)
X_test_tensor=torch.tensor(X_test_scaled,dtype=torch.float32)
y_test_tensor=torch.tensor(y_test,dtype=torch.long)

In [ ]:
train_dataset=TensorDataset(X_train_tensor,y_train_tensor)
test_dataset=TensorDataset(X_test_tensor,y_test_tensor)

In [ ]:
train_loader=DataLoader(train_dataset,batch_size=32,shuffle=True)
test_loader=DataLoader(test_dataset,batch_size=32)

In [ ]:
# Build our Model

class ANN(nn.Module):
    def __init__(self):
        super(ANN, self).__init__()

        self.model = nn.Sequential(
            nn.Linear(X.shape[1], 64),
            nn.ReLU(),
            nn.Linear(64, 64),
            nn.ReLU(),
            nn.Linear(64, 7)
        )

    def forward(self, x):
        return self.model(x)

In [ ]:
model = ANN()

# loss & optim
criteria = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters())

In [ ]:
# Training the NN

epochs = 100
for epoch in range(epochs):
    model.train()

    running_loss = 0.0

    for xb, yb in train_loader:
        optimizer.zero_grad()

        outputs = model(xb)
        loss = criteria(outputs, yb)
        loss.backward()
        optimizer.step() # params update

        running_loss += loss.item()

    train_loss = running_loss / len(train_loader)

    print(f"epoch = {epoch+1}/{epochs}, loss = {train_loss}")

epoch = 1/100, loss = 1.642627099285955
epoch = 2/100, loss = 1.0602163231891135
epoch = 3/100, loss = 0.6931340564852175
epoch = 4/100, loss = 0.5243130507676498
epoch = 5/100, loss = 0.44234876658605493
epoch = 6/100, loss = 0.38756969830264215
epoch = 7/100, loss = 0.35410634525444196
epoch = 8/100, loss = 0.32492435043272766
epoch = 9/100, loss = 0.30549098097759747
epoch = 10/100, loss = 0.27933952244727506
epoch = 11/100, loss = 0.2624235117565031
epoch = 12/100, loss = 0.2500221875050794
epoch = 13/100, loss = 0.22750175679507462
epoch = 14/100, loss = 0.2145530736964682
epoch = 15/100, loss = 0.2018558337636616
epoch = 16/100, loss = 0.19373501966828885
epoch = 17/100, loss = 0.18557354791656785
epoch = 18/100, loss = 0.1766449477037658
epoch = 19/100, loss = 0.171672273427248
epoch = 20/100, loss = 0.18251895742571872
epoch = 21/100, loss = 0.15718135100020014
epoch = 22/100, loss = 0.1519305339973906
epoch = 23/100, loss = 0.14614479924025742
epoch = 24/100, loss = 0.14110113890922588
epoch = 25/100, loss = 0.13889651016696639
epoch = 26/100, loss = 0.13496543207894202
epoch = 27/100, loss = 0.13226336977728034
epoch = 28/100, loss = 0.12802328995388487
epoch = 29/100, loss = 0.1280334962774878
epoch = 30/100, loss = 0.12965131032726038
epoch = 31/100, loss = 0.12089486387760742
epoch = 32/100, loss = 0.11661421839633714
epoch = 33/100, loss = 0.11466173908632735
epoch = 34/100, loss = 0.1103663063891556
epoch = 35/100, loss = 0.11157398023035216
epoch = 36/100, loss = 0.10487137994040614
epoch = 37/100, loss = 0.10536660820893619
epoch = 38/100, loss = 0.09811789623421172
epoch = 39/100, loss = 0.09730175793494868
epoch = 40/100, loss = 0.09575140711082064
epoch = 41/100, loss = 0.09983627656069786
epoch = 42/100, loss = 0.09298366316310737
epoch = 43/100, loss = 0.09248758139817612
epoch = 44/100, loss = 0.09378037909450739
epoch = 45/100, loss = 0.08476287094147308
epoch = 46/100, loss = 0.0839976462657037
epoch = 47/100, loss = 0.08260016005648219
epoch = 48/100, loss = 0.08793832434584266
epoch = 49/100, loss = 0.08274028644613597
epoch = 50/100, loss = 0.08569085994816344
epoch = 51/100, loss = 0.08360345698083224
epoch = 52/100, loss = 0.075717911205214
epoch = 53/100, loss = 0.0727473484635677
epoch = 54/100, loss = 0.07878240797182788
epoch = 55/100, loss = 0.06907500120122796
epoch = 56/100, loss = 0.0708214964353196
epoch = 57/100, loss = 0.07072543798257476
epoch = 58/100, loss = 0.06451164489692968
epoch = 59/100, loss = 0.06362838281885437
epoch = 60/100, loss = 0.06609986536204815
epoch = 61/100, loss = 0.06691569733716872
epoch = 62/100, loss = 0.06810375068174757
epoch = 63/100, loss = 0.06506605997033742
epoch = 64/100, loss = 0.058466392933674484
epoch = 65/100, loss = 0.05511847980644392
epoch = 66/100, loss = 0.05732429068049659
epoch = 67/100, loss = 0.05391459442351176
epoch = 68/100, loss = 0.05193704933575962
epoch = 69/100, loss = 0.05083622342056554
epoch = 70/100, loss = 0.056041519845957344
epoch = 71/100, loss = 0.05358193417930085
epoch = 72/100, loss = 0.047388611442368965
epoch = 73/100, loss = 0.049079937597169825
epoch = 74/100, loss = 0.05281784257892033
epoch = 75/100, loss = 0.046784198868250394
epoch = 76/100, loss = 0.04769498939909365
epoch = 77/100, loss = 0.04363435539214507
epoch = 78/100, loss = 0.04147659566091454
epoch = 79/100, loss = 0.03918781234761295
epoch = 80/100, loss = 0.03955319659460498
epoch = 81/100, loss = 0.04067546763943265
epoch = 82/100, loss = 0.03901087134347662
epoch = 83/100, loss = 0.04205082170159111
epoch = 84/100, loss = 0.035568452197248523
epoch = 85/100, loss = 0.04092642397660276
epoch = 86/100, loss = 0.03739822761196157
epoch = 87/100, loss = 0.03440045358856087
epoch = 88/100, loss = 0.033754898943816836
epoch = 89/100, loss = 0.033739425950562174
epoch = 90/100, loss = 0.03382879193953198
epoch = 91/100, loss = 0.03052988898454477
epoch = 92/100, loss = 0.03596299346131475
epoch = 93/100, loss = 0.03287143333379746
epoch = 94/100, loss = 0.02870081940098949
epoch = 95/100, loss = 0.028019057829742847
epoch = 96/100, loss = 0.030222765574960606
epoch = 97/100, loss = 0.026433639370066965
epoch = 98/100, loss = 0.0263176496335528
epoch = 99/100, loss = 0.026785049076273066
epoch = 100/100, loss = 0.03125990694388747

In [ ]:
# Evaluate
model.eval()

total = 0
correct = 0

with torch.no_grad():
    for xb, yb in test_loader:
        outputs = model(xb) # [0.2, 0.5, 1.3, -0.5, ..] - 7 vals
        _, predicted = torch.max(outputs, 1)

        correct += (predicted == yb).sum().item()
        total += yb.size(0) # actual samples in each batch

print("accuracy: ", correct/total * 100)

accuracy:  93.88888888888889