<a href="https://colab.research.google.com/github/vaishnavikokate20-debug/AIML/blob/main/Natural_Language_Processing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [35]:
df=pd.read_csv('train.txt.zip',sep=';',header=None,names=['text','emotions'])

In [36]:
df.head()

                                                text emotions
0                            i didnt feel humiliated  sadness
1  i can go from feeling so hopeless to so damned...  sadness
2   im grabbing a minute to post i feel greedy wrong    anger
3  i am ever feeling nostalgic about the fireplac...     love
4                               i am feeling grouchy    anger

In [37]:
df.isnull().sum()

text        0
emotions    0
dtype: int64

In [38]:
unique_emotions=df['emotions'].unique()
emotions_numbers={}
i=0
for emo in unique_emotions:
  emotions_numbers[emo]=i
  i +=1
df['emotions']=df['emotions'].map(emotions_numbers)

In [39]:
df

                                                    text  emotions
0                                i didnt feel humiliated         0
1      i can go from feeling so hopeless to so damned...         0
2       im grabbing a minute to post i feel greedy wrong         1
3      i am ever feeling nostalgic about the fireplac...         2
4                                   i am feeling grouchy         1
...                                                  ...       ...
15995  i just had a very brief time in the beanbag an...         0
15996  i am now turning and i feel pathetic that i am...         0
15997                     i feel strong and good overall         5
15998  i feel like this was such a rude comment and i...         1
15999  i know a lot but i feel so stupid because i ca...         0

[16000 rows x 2 columns]

In [40]:
df['text']=df['text'].apply(lambda x:x.lower())

In [41]:
import string
def remove_punc(txt):
  return txt.translate(str.maketrans('','',string.punctuation))

In [42]:
df['text']=df['text'].apply(remove_punc)

In [43]:
def remove_numbers(txt):
  new=""
  for i in txt:
      if not i.isdigit():
        new=new+i
  return new
df['text']=df['text'].apply(remove_numbers)

In [44]:
def remove_emojis(txt):
  new=""
  for i in txt:
      if i.isascii():
        new+=i
  return new
df['text']=df['text'].apply(remove_emojis)

In [45]:
import nltk

In [46]:
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

In [47]:
nltk.download('punkt')
nltk.download('stopwords')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [48]:
stop_words=set(stopwords.words('english'))
stop_words

{'a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 "he'd",
 "he'll",
 "he's",
 'her',
 'here',
 'hers',
 'herself',
 'him',
 'himself',
 'his',
 'how',
 'i',
 "i'd",
 "i'll",
 "i'm",
 "i've",
 'if',
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it'd",
 "it'll",
 "it's",
 'its',
 'itself',
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'only',
 'or',
 'other',
 'our',
 'ours',
 'ourselves',
 'out',
 'over',
 'own',
 're',
 's',
 'same',
 'shan',
 "shan't",
 'she',
 "she'd",
 "she'll",
 "she's",
 'should',
 "should've",
 'shouldn',
 "shouldn't",
 'so',
 'some',
 'such',
 't',
 'than',
 'that',
 "that'll",
 'the',
 'their',
 'theirs',
 'them',
 'themselves',
 'then',
 'there',
 'these',
 'they',
 "they'd",
 "they'll",
 "they're",
 "they've",
 'this',
 'those',
 'through',
 'to',
 'too',
 'under',
 'until',
 'up',
 've',
 'very',
 'was',
 'wasn',
 "wasn't",
 'we',
 "we'd",
 "we'll",
 "we're",
 "we've",
 'were',
 'weren',
 "weren't",
 'what',
 'when',
 'where',
 'which',
 'while',
 'who',
 'whom',
 'why',
 'will',
 'with',
 'won',
 "won't",
 'wouldn',
 "wouldn't",
 'y',
 'you',
 "you'd",
 "you'll",
 "you're",
 "you've",
 'your',
 'yours',
 'yourself',
 'yourselves'}

In [49]:
len(stop_words)

198

In [50]:
df.loc[1]['text']

'i can go from feeling so hopeless to so damned hopeful just from being around someone who cares and is awake'

In [51]:
def remove(txt):
  words=txt.split()
  cleaned=[]
  for i in words:
    if not i in stop_words:
      cleaned.append(i)
  return ' '.join(cleaned)

In [52]:
df['text']=df['text']. apply(remove)

In [53]:
df.loc[1]['text']

'go feeling hopeless damned hopeful around someone cares awake'

In [54]:
df.head()

                                                text  emotions
0                              didnt feel humiliated         0
1  go feeling hopeless damned hopeful around some...         0
2          im grabbing minute post feel greedy wrong         1
3  ever feeling nostalgic fireplace know still pr...         2
4                                    feeling grouchy         1

In [56]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(df['text'], df['emotions'], test_size=0.20, random_state=42)

In [83]:
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer

In [84]:
bow_vectorizer=CountVectorizer()

In [85]:
X_train_bow=bow_vectorizer.fit_transform(X_train)
X_test_bow=bow_vectorizer.transform(X_test)

In [86]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score

In [87]:
nb_model=MultinomialNB()
nb_model.fit(X_train_bow,y_train)

MultinomialNB()

In [88]:
pred_bow=nb_model.predict(X_test_bow)
print(accuracy_score(y_test,pred_bow))

0.768125

In [89]:
pred_bow

array([0, 5, 0, ..., 5, 5, 0])

In [90]:
TfidfVectorizer=TfidfVectorizer()

In [91]:
X_train_Tfidf=TfidfVectorizer.fit_transform(X_train)
X_test_Tfidf=TfidfVectorizer.transform(X_test)

In [92]:
nb2_model=MultinomialNB()
nb2_model.fit(X_train_Tfidf,y_train)

MultinomialNB()

In [93]:
y_pred=nb2_model.predict(X_test_Tfidf)

In [94]:
 print(accuracy_score(y_test,y_pred))

0.6609375

In [95]:
from sklearn.linear_model import LogisticRegression

In [96]:
logistic_model=LogisticRegression(max_iter=1000)

In [99]:
logistic_model.fit(X_train_Tfidf,y_train)

LogisticRegression(max_iter=1000)

In [100]:
log_pred=logistic_model.predict(X_test_Tfidf)

In [101]:
print(accuracy_score(y_test,log_pred))

0.8628125